<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Daggerfall Voice Engine</AssemblyName>
    <RootNamespace>DaggerfallVoiceEngine</RootNamespace>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Version>1.0.2</Version>
    <InformationalVersion>1.0.2</InformationalVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="KokoroSharp.CPU" Version="0.8.4" />
  </ItemGroup>
</Project>
